services:
  # mysql
  mysql:
    image: mysql:latest
    container_name: buytopia-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: zeroskill2400
      MYSQL_DATABASE: buytopia
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - buytopia-network
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # redis
  redis:
    image: redis:latest
    container_name: buytopia-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "zeroskill2400"]
    volumes:
      - redis_data:/data
    networks:
      - buytopia-network

  # zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: buytopia-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - buytopia-network

  # kafka
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: buytopia-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - buytopia-network

  # Eureka 서버
  eureka-api:
    build:
      context: ./api/eureka-api  # Eureka 서버 Dockerfile 경로
    container_name: eureka-api
    ports:
      - "8761:8761"
    environment:
      - EUREKA_SERVER_PORT=8761
      - SPRING_PROFILES_ACTIVE=prod  # prod 프로파일로 실행
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - buytopia-network

  gateway:
    build:
      context: ./api/gateway
    container_name: gateway
    ports:
      - "30000:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      mysql:
        condition: service_healthy
      eureka-api:
        condition: service_healthy
    networks:
      - buytopia-network

  web-bff:
    build:
      context: ./api/web-bff
    container_name: web-bff
    ports:
      - "18080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      mysql:
        condition: service_healthy
      eureka-api:
        condition: service_healthy
    networks:
      - buytopia-network

  admin-api:
    build:
      context: ./api/admin-api
    container_name: admin-api
    ports:
      - "18081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      mysql:
        condition: service_healthy
      eureka-api:
        condition: service_healthy
    networks:
      - buytopia-network

  user-api:
    build:
      context: ./api/user-api
    container_name: user-api
    ports:
      - "18082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      mysql:
        condition: service_healthy
      eureka-api:
        condition: service_healthy
    networks:
      - buytopia-network

  product-api:
    build:
      context: ./api/product-api
    container_name: product-api
    ports:
      - "18083:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      mysql:
        condition: service_healthy
      eureka-api:
        condition: service_healthy
    networks:
      - buytopia-network

  cms-api:
    build:
      context: ./api/cms-api
    container_name: cms-api
    ports:
      - "18084:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      mysql:
        condition: service_healthy
      eureka-api:
        condition: service_healthy
    networks:
      - buytopia-network

  commerce-api:
    build:
      context: ./api/commerce-api
    container_name: commerce-api
    ports:
      - "18086:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      mysql:
        condition: service_healthy
      eureka-api:
        condition: service_healthy
    networks:
      - buytopia-network


volumes:
  mysql_data:
  redis_data:
  kafka_data:

networks:
  buytopia-network:


# 백업시에 mysqldump -u root -p userapi(db명) > C:\backup\userapi_backup.sql(파일위치)
