services:
  # mysql
  mysql:
    image: mysql:latest
    container_name: buytopia-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: zeroskill2400
      MYSQL_DATABASE: buytopia
    volumes:
      - mysql_data:/var/lib/mysql

  # redis
  redis:
    image: redis:latest
    container_name: buytopia-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "zeroskill2400"]
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data:


# 백업시에 mysqldump -u root -p userapi(db명) > C:\backup\userapi_backup.sql(파일위치)
