server:
  port: 8087

spring:
  application:
    name: userapi
  datasource:
    url: jdbc:mysql://localhost:3306/userapi
    username: root
    password: zeroskill2400
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
          ddl-auto: update
#    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  h2:
    console:
      enabled: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: zeroskill2400@gmail.com
    password: ${MAIL_APP_KEY}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  redis:
    host: localhost
    port: 6379
    password: zeroskill2400

logging:
  config: classpath:log4j2.xml
  level:
    org:
      hibernate:
#        SQL: debug
#        type: trace

jwt:
  secret: mySecretKey
  access:
    expiration: 3600000
  refresh:
    expiration: 604800000
