server:
  port: 8761

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/buytopia  # 로컬 MySQL 사용
    username: root
    password: zeroskill2400
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # 로컬에서 Eureka 접속
    register-with-eureka: false
    fetch-registry: false
