server:
  port: 18080

spring:
  application:
    name: web-bff
  datasource:
    url: jdbc:mysql://localhost:3306/buytopia
    username: root
    password: zeroskill2400
    driver-class-name: com.mysql.cj.jdbc.Driver
  output:
    ansi:
      enabled: ALWAYS
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

