server:
  port: 8088

spring:
  application:
    name: admin-api
  datasource:
    url: jdbc:mysql://localhost:3306/buytopia
    username: root
    password: zeroskill2400
    driver-class-name: com.mysql.cj.jdbc.Driver
  output:
    ansi:
      enabled: ALWAYS