server:
  port: 8089

spring:
  application:
    name: common
  datasource:
    url: jdbc:mysql://localhost:3306/userapi
    username: root
    password: zeroskill2400
    driver-class-name: com.mysql.cj.jdbc.Driver
