server:
  port: 18086

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/buytopia?allowPublicKeyRetrieval=true&useSSL=false  # 도커 컨테이너에서 MySQL 사용
    username: root
    password: zeroskill2400
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
    #      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        highlight_sql: true
        format_sql: true
  output:
    ansi:
      enabled: ALWAYS
  kafka:
    bootstrap-servers: kafka:9093  # Kafka 브로커 서버 주소
    consumer:
      group-id: payment-group  # 컨슈머 그룹 ID
      auto-offset-reset: earliest
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

eureka:
  client:
    service-url:
      defaultZone: http://eureka-api:8761/eureka/  # 도커 내에서 Eureka 접속

logging.level:
  org.hibernate.type: trace

topics:
  payment-request: payment-request-topic
  payment-completed: payment-completed-topic